#!/bin/bash

##
##
## THIS A SCRIPT USED TO VERIFY THE COMPATIBILITY OF NEW VERSIONS OF CADP.
## ONE CAN ASSUME THAT, IF THE SCRIPT EXECUTES WITHOUT ANY ERROR, THE USED
## VERSION OF CADP IS COMPLIANT WITH THE LNT SPECIFICATIONS GENERATED BY
## VBPMN.
##
## NOTE 1: DO NOT HESITATE TO ADD NEW TEST CASES FOLLOWING THE SCHEMA PROPOSED
##         IN THE ACTUAL VERSION OF THIS FILE.
##
## NOTE 2: DO NOT HESITATE TO MODIFY THE VARIABLES ``CADP_CMP_RES_FALSE'',
##         ``CADP_CMP_RES_TRUE'' AND ``CADP_VERIF_RES_TRUE'' IF THE OUTPUT
##         OF CADP COMPARISON AND VERIFICATION SCRIPTS CHANGES.
##
##

TEST_FAILED=1
CADP_CMP_RES_FALSE="False"
CADP_CMP_RES_TRUE="TRUETrue"
CADP_VERIF_RES_TRUE="True"

cd update_tests;
rm -r tmp;
mkdir tmp;
cd tmp;

#Verify the capacity of the vbpmn script to obtain the expected results
#TEST 1

echo "Comparing Process_1a.pif with Process_1b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_1a.pif ../processes/Process_1b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 2

echo "Comparing Process_1a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_1a.pif ../processes/Process_1a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"    
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 3

echo "Comparing Process_2a.pif with Process_2b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_2a.pif ../processes/Process_2b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 4

echo "Comparing Process_2a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_2a.pif ../processes/Process_2a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"    
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 5

echo "Comparing Process_3a.pif with Process_3b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_3a.pif ../processes/Process_3b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 6

echo "Comparing Process_3a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_3a.pif ../processes/Process_3a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 7

echo "Comparing Process_4a.pif with Process_4b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_4a.pif ../processes/Process_4b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 8

echo "Comparing Process_4a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_4a.pif ../processes/Process_4a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 9

echo "Comparing Process_5a.pif with Process_5b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_5a.pif ../processes/Process_5b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 10

echo "Comparing Process_5a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_5a.pif ../processes/Process_5a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 11

echo "Comparing Process_6a.pif with Process_6b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_6a.pif ../processes/Process_6b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 12

echo "Comparing Process_6a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_6a.pif ../processes/Process_6a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 13

echo "Comparing Process_7a.pif with Process_7b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_7a.pif ../processes/Process_7b.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_FALSE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_FALSE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 14

echo "Comparing Process_7a.pif with itself..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_7a.pif ../processes/Process_7a.pif conservative"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_CMP_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_CMP_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Comparison succeeded!"
echo ""

#TEST 15

echo "Verifying property \"true\" on Process_1a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_1a.pif ../processes/Process_1a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 16

echo "Verifying property \"true\" on Process_1b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_1b.pif ../processes/Process_1b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 17

echo "Verifying property \"true\" on Process_2a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_2a.pif ../processes/Process_2a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 18

echo "Verifying property \"true\" on Process_2b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_2b.pif ../processes/Process_2b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 19

echo "Verifying property \"true\" on Process_3a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_3a.pif ../processes/Process_3a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 20

echo "Verifying property \"true\" on Process_3b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_3b.pif ../processes/Process_3b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 21

echo "Verifying property \"true\" on Process_4a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_4a.pif ../processes/Process_4a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 22

echo "Verifying property \"true\" on Process_4b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_4b.pif ../processes/Process_4b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 23

echo "Verifying property \"true\" on Process_5a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_5a.pif ../processes/Process_5a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 24

echo "Verifying property \"true\" on Process_5b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_5b.pif ../processes/Process_5b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 25

echo "Verifying property \"true\" on Process_6a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_6a.pif ../processes/Process_6a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 26

echo "Verifying property \"true\" on Process_6b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_6b.pif ../processes/Process_6b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 27

echo "Verifying property \"true\" on Process_7a.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_7a.pif ../processes/Process_7a.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

#TEST 28

echo "Verifying property \"true\" on Process_7b.pif..."

cmd="python ../../vbpmn_transformation/scripts/vbpmn.py ../processes/Process_7b.pif ../processes/Process_7b.pif property-implied --formula true"
res=$($cmd)
res=$(echo $res | tr -d '\n\t\r ')

if [ "$res" != $CADP_VERIF_RES_TRUE ]; then
    echo "/!\\ ERROR /!\\"
    echo "Command \"$cmd\" was expected to output \"$CADP_VERIF_RES_TRUE\", but it output \"$res\""
    echo "/!\\ ERROR /!\\"
    exit $TEST_FAILED
fi

rm *
echo "Verification succeeded!"
echo ""

echo "ALL THE COMPARISONS AND VERIFICATIONS SUCCEEDED: CURRENT CADP VERSION IS SAFE."

# Remove temp repository
cd ..;
rm -r tmp;
