#!/bin/sh 
# Script generated with SVL version 2.11

############
# PROLOGUE #
############
. "${SVL:-$CADP}"/src/svl/standard

SVL_DEBUG=""
SVL_SILENT=""
SVL_IGNORE=""
SVL_SOURCE_FILENAME=Process_1ngmb9d.svl

########
# BODY #
########
CAESAR_OPEN_OPTIONS="-silent -warning"
CAESAR_OPTIONS="-more cat -gc"
DEFAULT_PROCESS_FILE=Process_1ngmb9d.lnt
SVL_STATEMENT_LINE_NUMBER=6
SVL_RECORD_FOR_CLEAN \
	"Process_1ngmb9d_raw.bcg"
SVL_CHECK_FILE \
	"${DEFAULT_LOTOS_FILE:-$DEFAULT_PROCESS_FILE}" \
	"default"
SVL_COMPILE \
	"${DEFAULT_LOTOS_FILE:-$DEFAULT_PROCESS_FILE}" \
	"bcg" \
	"MAIN[Activity_1kwh79w, Activity_0zada8u, Activity_1k1z0h2, Activity_1ihs2pn, Activity_1nznv0p, Activity_1yint2p, Activity_0qskknw, Activity_09wb4yp, Activity_1u1z1yw]" \
	"Process_1ngmb9d_raw"
SVL_STATEMENT_LINE_NUMBER=8
SVL_RECORD_FOR_CLEAN \
	"Process_1ngmb9d.bcg"
SVL_CHECK_FILE \
	"Process_1ngmb9d_raw.bcg" \
	""
SVL_REDUCTION \
	"$DEFAULT_REDUCTION_TOOL" \
	"branching" \
	"" \
	"$DEFAULT_REDUCTION_METHOD" \
	"" \
	"Process_1ngmb9d_raw.bcg" \
	"" \
	"Process_1ngmb9d.bcg" \
	"" \
	""

############
# EPILOGUE #
############
SVL_PRINT_NEWLINE
SVL_EXIT
