//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 04:11:44 PM CET 
//

package fr.inria.convecs.optimus.pif;


import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConditionalSequenceFlow complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionalSequenceFlow">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/PIF}SequenceFlow">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.example.org/PIF}Condition"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionalSequenceFlow", propOrder = { "condition" })
public class ConditionalSequenceFlow extends SequenceFlow {

  @XmlElement(required = true)
  protected Condition condition;

  /**
   * Gets the value of the condition property.
   * 
   * @return possible object is {@link Condition }
   * 
   */
  public Condition getCondition() {
    return condition;
  }

  /**
   * Sets the value of the condition property.
   * 
   * @param value
   *          allowed object is {@link Condition }
   * 
   */
  public void setCondition(Condition value) {
    this.condition = value;
  }

}
