//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 04:11:44 PM CET 
//


package fr.inria.convecs.optimus.pif;


import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for Interaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Interaction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/PIF}Communication">
 *       &lt;sequence>
 *         &lt;element name="initiatingPeer" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="receivingPeers" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Interaction", propOrder = {
    "initiatingPeer",
    "receivingPeers"
})
public class Interaction
    extends Communication
{

    @XmlElement(required = true, type = Object.class)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Peer initiatingPeer;
    @XmlElementRef(name = "receivingPeers", namespace = "http://www.example.org/PIF", type = JAXBElement.class)
    protected List<JAXBElement<Object>> receivingPeers;

    /**
     * Gets the value of the initiatingPeer property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Peer getInitiatingPeer() {
        return initiatingPeer;
    }

    /**
     * Sets the value of the initiatingPeer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInitiatingPeer(Peer value) {
        this.initiatingPeer = value;
    }

    /**
     * Gets the value of the receivingPeers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receivingPeers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceivingPeers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getReceivingPeers()
    {
        if (receivingPeers == null) {
            receivingPeers = new ArrayList<>();
        }
        return this.receivingPeers;
    }

}
