//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 04:11:44 PM CET 
//


package fr.inria.convecs.optimus.pif;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Workflow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Workflow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodes" type="{http://www.example.org/PIF}WorkflowNode" maxOccurs="unbounded"/>
 *         &lt;element name="sequenceFlows" type="{http://www.example.org/PIF}SequenceFlow" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="initialNode" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="finalNodes" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Workflow", propOrder = {
		"nodes",
		"sequenceFlows",
		"initialNode",
		"finalNodes"
})
public class Workflow {

	@XmlElement(required = true)
	protected List<WorkflowNode> nodes;
	protected List<SequenceFlow> sequenceFlows;
	@XmlElement(required = true, type = Object.class)
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected InitialEvent initialNode;
	@XmlElementRef(name = "finalNodes", namespace = "http://www.example.org/PIF", type = JAXBElement.class, required = false)
	protected List<JAXBElement<Object>> finalNodes;

	/**
	 * Gets the value of the nodes property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the nodes property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getNodes().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link WorkflowNode }
	 * 
	 * 
	 */
	public List<WorkflowNode> getNodes() {
		if (nodes == null) {
			nodes = new ArrayList<WorkflowNode>();
		}
		return this.nodes;
	}

	/**
	 * Gets the value of the sequenceFlows property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the sequenceFlows property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSequenceFlows().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SequenceFlow }
	 * 
	 * 
	 */
	public List<SequenceFlow> getSequenceFlows() {
		if (sequenceFlows == null) {
			sequenceFlows = new ArrayList<SequenceFlow>();
		}
		return this.sequenceFlows;
	}


	/**
	 * Gets the value of the initialNode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Object }
	 *     
	 */
	public InitialEvent getInitialNode() {
		return initialNode;
	}

	/**
	 * Sets the value of the initialNode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Object }
	 *     
	 */
	public void setInitialNode(InitialEvent value) {
		this.initialNode = value;
	}

	/**
	 * Gets the value of the finalNodes property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the finalNodes property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getFinalNodes().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<Object>> getFinalNodes() {
		if (finalNodes == null) {
			finalNodes = new ArrayList<JAXBElement<Object>>();
		}
		return this.finalNodes;
	}
}
