/**
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * <p>
 * vbpmn
 * Copyright (C) 2015 Pascal Poizat (@pascalpoizat)
 * emails: pascal.poizat@lip6.fr
 */

import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecutor;
import org.apache.commons.exec.ExecuteException;
import org.apache.commons.exec.Executor;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class PifComparisonTests {

    public static final String CMD = "python";
    public static final String WORKINGDIR = "out/test/vbpmn/pif/";
    public static final String PROGRAM_PATH = "../../../production/vbpmn/";
    public static final String PROGRAM = "vbpmn.py";
    //public static final String OPTIONS = ""; // "--lazy" to have computation of BCG models only if needed, else ""
    public static final String OPTIONS = "--lazy"; // "--lazy" to have computation of BCG models only if needed, else ""
    public static final String TESTFILE = "tests.txt";
    public static final String REGEX_COMMENT = "^\\h*//.*$";
    public static final String REGEX_TEST = "^([+-])\\h(.*)\\h(.*)\\h(.*)$";
    public static final String REGEX_EMPTYLINE = "^\\h*$";
    public static final String OK = "+";
    public static final String NOK = "-";
    public static final String USELESS[] = {".o", ".f", ".t", ".err", ".lnt", ".lotos", ".svl", ".log", "_raw.bcg", "_work.bcg",
            "bisimulator", "bisimulator.bcg", "evaluator4", "evaluator.bcg", "generator",
            "formula.mcl", "res.txt"};
    public static List<String> USELESS_LIST;

    /**
     * Sets up the file exclusion list (based on filenames)
     */
    @BeforeClass
    public void setUp() {
        USELESS_LIST = Arrays.asList(USELESS);
    }

    /**
     * Deletes files generated by the tests
     */
    @AfterClass
    public void tearDown() {
        try {
            Object[] files = Files.list(Paths.get(WORKINGDIR))
                    .filter(x -> isUseless(x.toFile().getName()))
                    .toArray();
            for (Object file : files) {
                Files.delete((Path) file);
            }
        } catch (IOException e) {
            fail();
        }
    }

    /**
     * Decides if a file should be deleted after the tests (since created by them and useless)
     *
     * @param filename name of the file
     * @return true if useless, false else
     */
    public boolean isUseless(String filename) {
        boolean rtr = false;
        for (String exclusion_suffix : USELESS_LIST) {
            if (filename.endsWith(exclusion_suffix)) {
                rtr = true;
                break;
            }
        }
        return rtr;
    }

    /**
     * Performs equivalence/pre-order checking following the tests described in a file
     * <p>
     * note : there are issues with Process/ProcessBuilder for some contexts of use
     * see http://docs.oracle.com/javase/8/docs/api/java/lang/Process.html, http://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html
     * hence, we use Apache Commons Exec https://commons.apache.org/proper/commons-exec/
     */
    @Test(dataProvider = "get_data_from_test_file")
    public void run_all_tests(String expected_result, String rest) {
        int exitValue;
        CommandLine cmd = CommandLine.parse(String.format("%s -u %s%s %s %s", CMD, PROGRAM_PATH, PROGRAM, rest, OPTIONS));
        Executor executor = new DefaultExecutor();
        executor.setWorkingDirectory(new File(WORKINGDIR));
        int expected_result_as_int = 2;
        if (expected_result.equalsIgnoreCase(OK)) expected_result_as_int = 0;
        else if (expected_result.equalsIgnoreCase(NOK)) expected_result_as_int = 1;
        else fail();
        executor.setExitValue(expected_result_as_int);
        try {
            exitValue = executor.execute(cmd);
        } catch (IOException e) {
            System.out.println(e.getCause());
            fail();
        }
    }


    /**
     * Data provider from a test file
     */
    @DataProvider(name = "get_data_from_test_file")
    public Iterator<Object[]> get_data_from_test_file() {
        List<Object[]> data = new ArrayList<>();
        String line;
        FileInputStream filetests = null;
        Pattern p_test = Pattern.compile(REGEX_TEST);
        try {
            filetests = new FileInputStream(WORKINGDIR + TESTFILE);
            BufferedReader fin = new BufferedReader(new InputStreamReader(filetests));
            line = fin.readLine();
            while (line != null) {
                if (line.matches(REGEX_EMPTYLINE)) {
                    // nothing
                } else if (line.matches(REGEX_COMMENT)) {
                    System.out.println(line);
                } else if (line.matches(REGEX_TEST)) {
                    Matcher m_test = p_test.matcher(line);
                    if (m_test.matches()) {
                        String expected_result = m_test.group(1);
                        String file1 = m_test.group(2);
                        String file2 = m_test.group(3);
                        String options = m_test.group(4);
                        Object[] line_elements = new Object[2];
                        line_elements[0] = expected_result;
                        line_elements[1] = file1+" "+file2+" "+options;
                        data.add(line_elements);
                    } else {
                        fail();
                    }
                } else {
                    System.out.println(String.format("cannot parse line: %s", line));
                    fail();
                }
                line = fin.readLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
            fail();
        }
        return data.iterator();
    }

}
